In [2]:
from sklearn.model_selection import ParameterGrid

In [4]:
parameter = dict(amp = [0.001, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2,  
                        0.5, 0.7, 1, 2, 5] , 
                 lcx = [1, 0.5], 
                 bm = [1, 4, 10],
                 lcy = [0.5, 2, 30])

params_grids = ParameterGrid(parameter)

In [1]:
from DataBase import DataBase
from utils.utils import *

In [2]:
import numpy as np

In [5]:
IQ_LIST = np.array(np.load("/media/andrea/Crucial X6/scholar/Master/stage/data/linear_profile_amp/a_0.0003/IQ_0.npy"))

In [9]:
delay_list = np.array([delay(*IQ_LIST)])
pulse_witdh = np.array([delay_dispersion(*IQ_LIST)])

In [10]:
delay_list, pulse_witdh

(array([4.37745098e-09+0.j]), array([8.99509804e-10+0.j]))

In [11]:
data = dict(id = 1 , amplitude = 0.05, lcx = 0.1, lcy =0.1 , bm = 1, time_list = IQ_LIST[0], pulse_list = IQ_LIST[1], delay_list = delay_list, pulse_width = pulse_witdh)

In [12]:
db = DataBase('./test.db')
db.insert(data)


In [15]:
db.c.execute("SELECT  pulse_list, delay_list, pulse_width FROM data where id = 1")
p,d,c = db.c.fetchall()[0]

In [17]:
p,d,c

(array([0.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , ..., 0.51125656-0.07488921j,
        0.50102267-0.06900563j, 0.49212666-0.07097344j]),
 array([4.37745098e-09+0.j]),
 array([8.99509804e-10+0.j]))

In [44]:
db.c.execute("""UPDATE data SET pulse_list = ?  WHERE id = 1; """, (np.array([0]),))
db.conn.commit()

In [3]:
db = DataBase('./test6.db')
db.c.execute("SELECT  pulse_list, delay_list FROM data where id = 1")
p,d = db.c.fetchall()[0]

In [4]:
d

array([1.0000e-03, 1.3000e-03, 1.7000e-03, 2.3000e-03, 3.0000e-03,
       4.0000e-03, 5.3000e-03, 7.0000e-03, 9.2000e-03, 1.2200e-02,
       1.6100e-02, 2.1300e-02, 2.8100e-02, 3.7100e-02, 4.8900e-02,
       6.4600e-02, 8.5300e-02, 1.1260e-01, 1.4870e-01, 1.9640e-01,
       2.5930e-01, 3.4240e-01, 4.5200e-01, 5.9680e-01, 7.8800e-01,
       1.0405e+00, 1.3738e+00, 1.8139e+00, 2.3950e+00, 3.1623e+00])

In [31]:
a = db.c.execute("""SELECT EXISTS(SELECT id FROM data where id = 0)""")

In [32]:
db.c.fetchall()[0][0]

0